// <auto-generated />
using HotelListing.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.API.Migrations
{
    [DbContext(typeof(HotelListingDBContext))]
    [Migration("20220626114413_AddingSeeddatafortables")]
    partial class AddingSeeddatafortables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelListing.API.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "India",
                            shortName = "IND"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Australia",
                            shortName = "AUS"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Newzeland",
                            shortName = "NZ"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Models.Hotels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ratahara",
                            CountryId = 1,
                            Name = "Landmark Hotel",
                            Rating = 5.2999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Address = "NehruNagar",
                            CountryId = 2,
                            Name = "sanskaar Hotel",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Malviya Nagar ",
                            CountryId = 2,
                            Name = "Dang Hotel",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("HotelListing.API.Models.Hotels", b =>
                {
                    b.HasOne("HotelListing.API.Models.Country", "country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("HotelListing.API.Models.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
